name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/quantum-calibration-devops
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: List root directory
        run: ls -l
        
      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t gordey2024/quantum-calibration:latest .
          - name: Debug Docker username secret
          run: |
            if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
              echo "DOCKER_USERNAME is empty!"
              exit 1
            else
              echo "DOCKER_USERNAME is set."
            fi
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Push Docker image
        run: |
          docker push gordey2024/quantum-calibration:latest
